service:
  golangci-lint-version: 1.53.3
run:
  deadline: 10m
  skip-dirs:
    - cover
  modules-download-mode: mod

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - errcheck
      text: "Error return value of `c.SetCheckpoint` is not checked"
    - linters:
        - errcheck
      text: "Error return value of `c.deregisterConsumer` is not checked"
    - linters:
        - errcheck
      text: "Error return value of `c.save` is not checked"
    - linters:
        - errcheck
      text: "Error return value of `dynamodbattribute.UnmarshalMap` is not checked"

linters:
  enable:
    - exportloopref
    - goimports
  disable:
    - structcheck
